plugins {
    id 'fabric-loom' version '1.13.3'
    id 'maven-publish'
    id "com.hypherionmc.modutils.modpublisher" version "2.1.6"
}

version = project.mod_version
group = project.maven_group

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()

    // РЕПОЗИТОРИИ ДЛЯ ЗАВИСИМОСТЕЙ (ПРИОРИТЕТНЫЕ)
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://cursemaven.com"
    }
    maven {
        url 'https://jitpack.io'
    }
    maven {
        url "https://maven.shedaniel.me/"
    }
    maven {
        url "https://maven.siphalor.de/"
    }
    maven {
        url "https://maven.isxander.dev/releases"
    }
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.net/"
    }
    // Упавший репозиторий опущен ниже
    maven {
        url "https://maven.terraformersmc.com/"
    }
    flatDir {
        dir 'libs'
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "com.corosus.coroutil:coroutil-fabric:${project.minecraft_version}-${project.coroutil_version}"

    // Fabric API.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Тянем ForgeConfigAPIPort с Modrinth напрямую
    include(modImplementation("maven.modrinth:forge-config-api-port:21.11.1-fabric,1.21.11"))
    implementation 'com.electronwill.night-config:core:3.7.3'
    implementation 'com.electronwill.night-config:toml:3.7.3'
}

//If there's mixins
loom {
    accessWidenerPath = file("src/main/resources/${project.mod_id}.accesswidener")
    mixin {
        defaultRefmapName = "${project.mod_id}.refmap.json"
    }
}

sourceSets {
    main {
        java {
            exclude "com/corosus/${project.mod_id}/api/forge/**"
            exclude "com/corosus/${project.mod_id}/loader/forge/**"
            exclude "com/corosus/${project.mod_id}/loader/neoforge/**"
        }
    }
}

base {
    archivesName = "${project.archives_base_name}-fabric"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "mod_id": project.mod_id, "version": project.version, "mod_name": project.mod_name, "mod_description": project.mod_description, "mod_authors": project.mod_authors, "mod_license": project.mod_license
    }

    exclude("META-INF/mods.toml")
    exclude("META-INF/neoforge.mods.toml")
    exclude("META-INF/accesstransformer.cfg")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSE_TOKEN")
    }

    setDebug(false)
    setCurseID("945479")
    setModrinthID("what-are-they-up-to")
    setVersionType("release")
    setChangelog("https://raw.githubusercontent.com/Corosauce/WATUT/refs/heads/1.21.4/changelog.md")
    setProjectVersion("${project.version}")
    setDisplayName("${project.mod_id}-fabric-${project.mod_version}.jar")
    setGameVersions("${project.minecraft_version}")
    setLoaders("fabric")
    setCurseEnvironment("both")
    setIsManualRelease(false)
    setArtifact("build/libs/${project.mod_id}-fabric-${project.mod_version}.jar")
    setDisableMalwareScanner(true)
    setJavaVersions(JavaVersion.VERSION_21, 21)
    setDisableEmptyJarCheck(true)

    modrinthDepends {
        required "coroutil"
    }

    curseDepends {
        required "coroutil"
    }
}
